services:
  server:
    image: ghcr.io/hrnco/http2tcp-signing-server:latest
    ports:
      - "8080:80"
    environment:
      APP_ENV: dev
    volumes:
      - keys:/keys

  agent:
    image: ghcr.io/hrnco/http2tcp-local-agent:latest
#    build:
#      context: .
#      dockerfile: .docker/Dockerfile
    ports:
      - "34279:80"
    environment:
      HTTP2TCP_CORS_ALLOW_ORIGIN: http://localhost:8080
    volumes:
#      - ./:/var/www/html
      - agent_data:/data
    restart: unless-stopped

volumes:
  keys:
  agent_data:
