services:

  tcp-echo:
    image: alpine/socat:latest
    command: ["-v", "tcp-listen:9000,reuseaddr,fork", "exec:/bin/cat"]

  server:
    image: ghcr.io/hrnco/http2tcp-signing-server:1.17
    ports:
      - "8080:80"
    environment:
      APP_ENV: dev
      TEST_DEFAULT_DEVICE_PORT: 9000
      TEST_DEFAULT_DEVICE_IP: tcp-echo
      #TTL_SECONDS: 1 # Short TTL for testing
    volumes:
      - keys:/keys

  agent:
    image: ghcr.io/hrnco/http2tcp-local-agent:latest
#    build:
#      context: .
#      dockerfile: .docker/Dockerfile
    ports:
      - "34279:80"
    environment:
      HTTP2TCP_CORS_ALLOW_ORIGIN: http://localhost:8080
      HTTP2TCP_MULTI_PAIRING: "true"
      #HTTP2TCP_MULTI_PAIRING: "true" # only for testing|dev
    volumes:
      - ./:/var/www/html
      - agent_data:/data

volumes:
  keys:
  agent_data:
